question_data = [
    {"text": "The first computer virus was created in the 1980s.", "answer": "True"},
    {"text": "An IP address identifies a device on a network.", "answer": "True"},
    {"text": "The Linux operating system is open-source.", "answer": "True"},
    {"text": "HTML stands for HyperText Markup Language.", "answer": "True"},
    {"text": "A bit is short for binary digit.", "answer": "True"},
    {"text": "The 'http' in URLs stands for HyperText Transfer Protocol.", "answer": "True"},
    {"text": "JavaScript is a server-side programming language.", "answer": "False"},
    {"text": "The binary system uses base-10 numbering.", "answer": "False"},
    {"text": "A router connects multiple networks and directs data between them.", "answer": "True"},
    {"text": "Machine learning is a subset of artificial intelligence.", "answer": "True"},
    {"text": "A database management system (DBMS) manages database schemas and data.", "answer": "True"},
    {"text": "The first computer was the ENIAC.", "answer": "True"},
    {"text": "SQL is used to create and manage relational databases.", "answer": "True"},
    {"text": "An algorithm is a set of steps to accomplish a task.", "answer": "True"},
    {"text": "Cloud computing refers to using computing resources over the internet.", "answer": "True"},
    {"text": "A compiler translates high-level code into machine code.", "answer": "True"},
    {"text": "The 'null' keyword in programming indicates an empty or non-existent value.", "answer": "True"},
    {"text": "The C++ programming language is known for its simplicity.", "answer": "False"},
    {"text": "A firewall is used to protect networks from unauthorized access.", "answer": "True"},
    {"text": "The 'Python' programming language is named after a snake.", "answer": "False"},
    {"text": "Encryption is the process of converting data into a readable format.", "answer": "False"},
    {"text": "Open-source software is software with source code that anyone can inspect, modify, and enhance.", "answer": "True"},
    {"text": "An operating system manages hardware and software resources on a computer.", "answer": "True"},
    {"text": "The 'for' loop is used for iteration in programming.", "answer": "True"},
    {"text": "In computing, 'RAM' stands for Random Access Memory.", "answer": "True"},
    {"text": "A website’s frontend is responsible for server-side operations.", "answer": "False"},
    {"text": "The 'IPv6' protocol provides a larger address space compared to 'IPv4'.", "answer": "True"},
    {"text": "CSS is used to style the layout of a website.", "answer": "True"},
    {"text": "Git is a version control system.", "answer": "True"},
    {"text": "Virtual Reality (VR) requires physical hardware to function.", "answer": "True"},
    {"text": "A hash function is used to encrypt data.", "answer": "False"},
    {"text": "Machine learning can be classified into supervised and unsupervised learning.", "answer": "True"},
    {"text": "In programming, 'IDE' stands for Integrated Development Environment.", "answer": "True"},
    {"text": "Data stored in ROM is volatile and loses its contents when power is off.", "answer": "False"},
    {"text": "The 'Linux' operating system was created by Linus Torvalds.", "answer": "True"},
    {"text": "A 'bug' in computer programming refers to a hardware malfunction.", "answer": "False"},
    {"text": "The 'command line interface' allows users to interact with the operating system using text commands.", "answer": "True"},
    {"text": "In computer science, 'OOP' stands for Object-Oriented Programming.", "answer": "True"},
    {"text": "A 'server' is a type of computer that serves data to other computers.", "answer": "True"},
    {"text": "Java and JavaScript are the same programming language.", "answer": "False"},
    {"text": "The 'root directory' is the top-level directory in a file system.", "answer": "True"},
    {"text": "In computing, 'HTTP' stands for HyperText Transfer Protocol.", "answer": "True"},
    {"text": "A 'domain name' is a unique identifier for a website on the internet.", "answer": "True"},
    {"text": "The 'Python' programming language was created by Guido van Rossum.", "answer": "True"},
    {"text": "In 'Big O' notation, O(1) represents linear time complexity.", "answer": "False"},
    {"text": "The 'client-server' model involves a client requesting resources from a server.", "answer": "True"},
    {"text": "'Blockchain' technology is used for creating digital currencies like Bitcoin.", "answer": "True"},
    {"text": "The 'kernel' is the core component of an operating system.", "answer": "True"},
    {"text": "In binary, the number 2 is represented as '10'.", "answer": "True"},
    {"text": "A 'bit' is the smallest unit of data in computing.", "answer": "True"},
    {"text": "In computing, 'GUI' stands for Graphical User Interface.", "answer": "True"},
    {"text": "The 'TCP/IP' model is used for data transmission over networks.", "answer": "True"},
    {"text": "A 'neural network' is a type of algorithm used in machine learning.", "answer": "True"},
    {"text": "In programming, 'HTML' stands for HyperText Markup Language.", "answer": "True"},
    {"text": "A 'variable' in programming holds a value that can change during execution.", "answer": "True"},
    {"text": "The 'binary search' algorithm has a time complexity of O(n).", "answer": "False"},
    {"text": "An 'API' is an Application Programming Interface.", "answer": "True"},
    {"text": "A 'compile-time error' is an error that occurs during the program's execution.", "answer": "False"},
    {"text": "In 'SQL', the 'SELECT' statement is used to retrieve data from a database.", "answer": "True"},
    {"text": "The 'heap' is a type of data structure used for sorting elements.", "answer": "True"},
    {"text": "In computer science, 'binary' is a base-8 numbering system.", "answer": "False"}
]

