question_data =[
    {"text": "The Earth is the third planet from the Sun.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Shakespeare wrote 'The Great Gatsby'.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "A leap year has 366 days.", "answer": "True"},
    {"text": "Humans have more than five senses.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Berlin.", "answer": "False"},
    {"text": "Australia is both a country and a continent.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Albert Einstein was awarded the Nobel Prize in Literature.", "answer": "False"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "Jupiter is the largest planet in our solar system.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "Leonardo da Vinci painted 'The Last Supper'.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "There are seven continents on Earth.", "answer": "True"},
    {"text": "The Amazon Rainforest is located in Africa.", "answer": "False"},
    {"text": "Gold is a metal.", "answer": "True"},
    {"text": "The Statue of Liberty is located in Los Angeles.", "answer": "False"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "The human brain weighs about 3 pounds.", "answer": "True"},
    {"text": "The sun rises in the west.", "answer": "False"},
    {"text": "New York City is the capital of the United States.", "answer": "False"},
    {"text": "Pluto is considered a planet in our solar system.", "answer": "False"},
    {"text": "Bees are essential for pollination.", "answer": "True"},
    {"text": "The largest desert in the world is the Sahara Desert.", "answer": "True"},
    {"text": "The Great Wall of China was built in one year.", "answer": "False"},
    {"text": "A triangle has four sides.", "answer": "False"},
    {"text": "Mount Fuji is a volcano in Japan.", "answer": "True"},
    {"text": "The Nile River is the longest river in the world.", "answer": "True"},
    {"text": "Leonardo da Vinci painted the Sistine Chapel.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The currency of the UK is the Pound Sterling.", "answer": "True"},
    {"text": "A year on Mars is longer than a year on Earth.", "answer": "True"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Venus is known as the Red Planet.", "answer": "False"},
    {"text": "The Sahara Desert is the driest place on Earth.", "answer": "True"},
    {"text": "The Dead Sea is the lowest point on Earth's surface.", "answer": "True"},
    {"text": "The Great Barrier Reef is located in the Atlantic Ocean.", "answer": "False"},
    {"text": "Elephants are the largest land animals on Earth.", "answer": "True"},
    {"text": "Cows are herbivores.", "answer": "True"},
    {"text": "Hummingbirds are the only birds that can fly backwards.", "answer": "True"},
    {"text": "Mammals lay eggs.", "answer": "False"},
    {"text": "Venus is the second planet from the Sun.", "answer": "True"},
    {"text": "The capital of Brazil is Rio de Janeiro.", "answer": "False"},
    {"text": "A giraffe's neck has the same number of vertebrae as a human's neck.", "answer": "True"},
    {"text": "The Eiffel Tower was completed in 1889.", "answer": "True"},
    {"text": "Antarctica is the coldest continent.", "answer": "True"}
]

